# Generated by Django 4.1.7 on 2023-05-08 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_registration_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='IMAGE',
            field=models.ImageField(default=True, upload_to='registration_images/'),
            preserve_default=False,
        ),
    ]
