# Generated by Django 4.1.7 on 2023-05-08 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_registration_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='IMAGE',
            field=models.ImageField(upload_to='static/image/registration_images/'),
        ),
    ]
