# Generated by Django 4.1.7 on 2023-05-08 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_registration_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='TRADE',
            field=models.CharField(choices=[('Electrician', 'Electrician'), ('Plumber', 'Plumber')], max_length=20),
        ),
    ]
