# Generated by Django 4.1.7 on 2023-05-11 06:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myapp', '0007_contactus'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='ADDRESS',
            field=models.TextField(default=True),
        ),
        migrations.AddField(
            model_name='registration',
            name='USER',
            field=models.OneToOneField(default=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
