# Generated by Django 4.1.7 on 2023-05-11 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_registration_address_registration_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='ADDRESS',
            field=models.TextField(),
        ),
    ]
